// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtb_uart_fifo_top.cpp"
#include "Vtb_uart_fifo_top___024root__DepSet_h6c9e2eaf__0.cpp"
#include "Vtb_uart_fifo_top___024root__DepSet_hdd28c2a2__0.cpp"
#include "Vtb_uart_fifo_top__main.cpp"
#include "Vtb_uart_fifo_top__Trace__0.cpp"
#include "Vtb_uart_fifo_top___024root__Slow.cpp"
#include "Vtb_uart_fifo_top___024root__DepSet_h6c9e2eaf__0__Slow.cpp"
#include "Vtb_uart_fifo_top___024root__DepSet_hdd28c2a2__0__Slow.cpp"
#include "Vtb_uart_fifo_top__Syms.cpp"
#include "Vtb_uart_fifo_top__Trace__0__Slow.cpp"
#include "Vtb_uart_fifo_top__TraceDecls__0__Slow.cpp"
