//==============================================================================
// desc_ring_mgr.sv
// Descriptor Ring Manager: maintains insert/extract pointers for the
// scatter-gather descriptor ring. Ring lives in host memory; hardware
// mirrors insert/extract pointers locally and exposes them via BAR registers.
//
// Ring depth is fixed at compile time. Pointer width includes one extra MSB
// beyond the index width so that full/empty can be distinguished unambiguously
// (classic FIFO pointer trick, applied here to a descriptor ring instead of
// a data FIFO).
//==============================================================================
module desc_ring_mgr #(
    parameter int RING_DEPTH  = 128,                       // must be power of 2
    parameter int PTR_WIDTH   = $clog2(RING_DEPTH) + 1      // extra bit for wrap disambiguation
)(
    input  logic                  clk,
    input  logic                  rst_n,

    // Software-facing (BAR-mapped) interface
    input  logic [PTR_WIDTH-1:0]  sw_insert_ptr_wr,   // value software writes to advance insert ptr
    input  logic                  sw_insert_ptr_wr_en,
    output logic [PTR_WIDTH-1:0]  hw_extract_ptr_rd,  // value software reads to know hw progress

    // Internal engine interface
    output logic [PTR_WIDTH-1:0]  insert_ptr,
    output logic [PTR_WIDTH-1:0]  extract_ptr,
    input  logic                  extract_ptr_update,  // pulse: advance extract_ptr by 1
    input  logic                  extract_valid_req,   // engine wants to know if a descriptor is available

    output logic                  ring_empty,
    output logic                  ring_full,
    output logic                  extract_valid,       // 1 = a valid descriptor is available to fetch

    // Debug / assertion taps (used by tb/assertions/sva_descriptor_invariants.sv via bind)
    output logic                  insert_ptr_update_dbg,
    output logic                  extract_ptr_update_dbg
);

    logic [PTR_WIDTH-1:0] insert_ptr_r, extract_ptr_r;

    // ---------------------------------------------------------------
    // Insert pointer: driven by software via BAR write. In a real
    // implementation this register is memory-mapped; sw_insert_ptr_wr_en
    // is generated by the AXI4-Lite/MM register block, not shown here.
    // ---------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            insert_ptr_r <= '0;
        end else if (sw_insert_ptr_wr_en) begin
            insert_ptr_r <= sw_insert_ptr_wr;
        end
    end

    // ---------------------------------------------------------------
    // Extract pointer: driven by hardware as descriptors are consumed.
    // Only advances one at a time, gated by extract_ptr_update pulse
    // from desc_fetch.sv after WRITEBACK completes for that descriptor.
    // ---------------------------------------------------------------
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            extract_ptr_r <= '0;
        end else if (extract_ptr_update) begin
            extract_ptr_r <= extract_ptr_r + 1'b1;
        end
    end

    assign insert_ptr  = insert_ptr_r;
    assign extract_ptr = extract_ptr_r;
    assign hw_extract_ptr_rd = extract_ptr_r;

    // ---------------------------------------------------------------
    // Empty/full computed using the extra-bit trick:
    // empty  when insert_ptr == extract_ptr (all bits equal, including MSB)
    // full   when index bits equal but MSB differs (wrapped exactly RING_DEPTH ahead)
    // ---------------------------------------------------------------
    assign ring_empty = (insert_ptr_r == extract_ptr_r);
    assign ring_full  = (insert_ptr_r[PTR_WIDTH-2:0] == extract_ptr_r[PTR_WIDTH-2:0]) &&
                         (insert_ptr_r[PTR_WIDTH-1]   != extract_ptr_r[PTR_WIDTH-1]);

    assign extract_valid = extract_valid_req && !ring_empty;

    // Debug taps for assertion binding
    assign insert_ptr_update_dbg  = sw_insert_ptr_wr_en;
    assign extract_ptr_update_dbg = extract_ptr_update;

endmodule
